### ISSUE TITLE
[Question] Is it possible to resemble folder structure from .json takeout files?

### ISSUE THREAD

**Issue by masiv1001** [TheLastGimbus/GooglePhotosTakeoutHelper#108]
Is it possible to do just that? I'm not talking about albums, since I hadn't set any, but the original folder, it looks like there is some metadata about this:

![image](https://user-images.githubusercontent.com/79378620/162984682-86c58ef3-da68-40f2-9817-51555171dc24.png)
This is what the .json file looks like to me

All of this because I've used to use google photos in my phone with the sync feature, but it just became a mess (screenshots, camera photos, stickers, and so on all in one single folder.

Using --albums json didn't do a thing, because these files don't have albums, only "LocalFolderName"

**Comment by TheLastGimbus** [comment]
What do you want to achive? You want to put photos "Stickers" in separate folder (rather than one big)?

**Comment by lucasff** [comment]
I think it's useful, to recreate that. Some images come from the Camera, but some from WhatsApp or Instagram.
If that's done on the filesystem, it would be interesting. Could we perhaps have a hard link that points to the original file, so that disk space is not wasted?

**Comment by TheLastGimbus** [comment]
@lucasff you're talking about albums. We talked a lot about them already - they are really hard to implement (because, as everything in google takeout - unreliable). Current, experimental solution is that you can get a `.json` file with which photo corresponds to which folder. You can build some small script upon this file yourself - but currently, I didn't see good options to implement it officially (and i'm lazy and don't have time for this):

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/issues/10#issuecomment-738517216

> hard link

hard links/symlinks/shortcuts are platform (windioza/unix/macos) dependent :/

**Comment by TheLastGimbus** [comment]
As of `v3`, albums should be working very well, tho still no idea how to output them
