### ISSUE TITLE
Keep original folder structure

### ISSUE THREAD

**Issue by mario-mestrovic** [TheLastGimbus/GooglePhotosTakeoutHelper#126]
Hi! First of all - great little tool, I really appreciate this as it helped me get my photos to my Synology NAS!
What I think can be useful is keeping the original folder structure. Why? Because some of the folders are not years and months but real album names.

Would like to know what do you think about this proposal. Also, I can help contributing!

**Comment by TheLastGimbus** [comment]
Hmm... for that, there were already attempts on supporting albums 👀 look at #36... we tried to implement albums somehow, but it turned out that we don't know how... finally, we landed on just a json file that you could later use to copy photos back to albums...

We could try to add post-run step that would do that for you... but this is very experimental, but you could try 👍

**Comment by TheLastGimbus** [comment]
Please disguss in #135 if you have any proposals
