### ISSUE TITLE
Why tf do you write "Windoza" instead of Windows. Lmao

### ISSUE THREAD

**Issue by francescoavagliano** [TheLastGimbus/GooglePhotosTakeoutHelper#158]

**Comment by TheLastGimbus** [comment]
One time I was chatting with my tech-savy-friends, and i asked one of them if he wanted to play a game or something like that, and he said

```
- I don't have windoza
- *windows
- xDDD
```

So since then (about 5 years ago) I'm still using that because it fits. See how: `"Windows crashed again"` is less fun than `"wℹ️ND🅾️z🅰️ crashed again"`

Maybe it sounds better in Polish tho 🤷

Anyway, this repo is pure example of why, ekhm "the flagship microsoft product" should be called windoza
