### ISSUE TITLE
Getting error "Input folder does not exist :/ [gpth quitted :( (code 11) ]"

### ISSUE THREAD

**Issue by javuls** [TheLastGimbus/GooglePhotosTakeoutHelper#193]
im running on an M1 mac and I installed rosetta before hand and followed all the instructions.
The only thing im doin differently is that my files are stored on an external ssd and im trying to run the program for the files located on the ssd.

**Comment by TheLastGimbus** [comment]
Can you show me some screenshots of what's happening?

**Comment by 360fun** [comment]
I had the same problem, and in my case, the issue was due to using an external drive that had the same name as an internal partition. In Terminal, macOS automatically renamed the external drive by adding a `/1` (like `/Volumes/HD\ 1/`). Maybe the space caused the error—didn’t dig further...

I renamed the drive to `HD2`, and that fixed the issue! It took me a while to figure it out… 🥵
Hope this helps someone else in a similar situation. 🙏
