### ISSUE TITLE
Getting error 13 each time I try to run the executable

### ISSUE THREAD

**Issue by Schultz05** [TheLastGimbus/GooglePhotosTakeoutHelper#200]
Hi,

I've been trying lately to organize my google takeout photos and each time a receive the following error as shown below Am I doing something wrong instead?

See the commands/options/errors:

```
GooglePhotosTakeoutHelper v3.4.1
Hi there! This tool will help you to get all of your photos from Google Takeout to one nice tidy folder

(If any part confuses you, read the guide on:
https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper )

Select the directory where you unzipped all your takeout zips
(Make sure they are merged => there is only one "Takeout" folder!)
[press enter to continue]

Cool!

Now, select output folder - all photos will be extracted there
[press enter to continue]

Cool!

Do you want your photos in one big chronological folder, or divided to folders by year/month?
[1] (default) - one big folder
[2] - year/month folders
(Type 1 or 2 or press enter for default):
2
Okay, will divide to folders!

What should be done with albums?
[0] shortcut: [Recommended] Album folders with shortcuts/symlinks to original photos. Recommended as it will take the least space, but may not be portable when moving across systems/computes/phones etc
[1] duplicate-copy: Album folders with photos copied into them. This will work across all systems, but may take wayyy more space!!
[2] json: Put ALL photos (including Archive and Trash) in one folder and make a .json file with info about albums. Use if you're a programmer, or just want to get everything, ignoring lack of year-folders etc.
[3] nothing: Just ignore them and put year-photos into one folder. WARNING: This ignores Archive/Trash !!!
0
Okay, doing: shortcut

Okay, running... searching for everything in input folder...
...oh :(
...
I couldn't find any D: reasons for this may be:
  - you've already ran gpth and it moved all photos to output -
    delete the input folder and re-extract the zip
  - your Takeout doesn't have any "year folders" -
    visit https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper
    again and request new, correct Takeout
After fixing this, go ahead and try again :)
[gpth quitted :( (code 13) - press enter to close]
```

**Comment by Schultz05** [comment]
Do note that I created a google takeout based on album selection. Could that be the problem?

**Comment by TheLastGimbus** [comment]
Well.. does your takeout actually contains photos? Show me the screenshots/something

Yes, selecting only albums could be the problem. Best way is to select everything, but you can try albums only too

**Comment by edtfin** [comment]
I have the same prob. @Schultz05

**Comment by TheLastGimbus** [comment]
@edtfin same as @Schultz05  - you guys need to give me verbose descriptions on how you have your takeouts downloaded and unzipped...

**Comment by TheLastGimbus** [comment]
all of the code and actually even pipeline of uploading binaries is publicly visible :shrug: i don't think there's even a way i could upload a virus here...

**Comment by Tandagore** [comment]
Hey, trying to be a bit more helpful here: I'm currently having the same problem, mostly that I don't actually know how the folder structure should be looking for the Helper to actually recognize/be able to work with the dump. I'm working on an older dump (about three years old) and the photos have since been removed from Google, so getting a new dump sadly isn't an option for me. 
Folder Structure currently looks like this: D:\Google\Takeout\Google Photos with the last folder containing all the subfolders (all named like YEAR-MONTH-DAY, i.e. 2016-08-18), which have the pictures, the metadata and the json in them. 
I'm getting the same error, how would the folder structure need to look like to be processable?

**Comment by TheLastGimbus** [comment]
@Tandagore sorry for late reply:

You have the same problem as #182 - read discussion there

But you already removed them from google...

Hmmm, okay, here's what you can do:
1. Make a copy of original takeout zip not to lose it
2. Move all files from all `YEAR-MONTH-DAY` folders to one folder named `Photos from 2015` (or whatever year) - it can be a single folder, with pics from different years, doesn't really matter
3. Try to run `gpth` - shooould work :crossed_fingers:

**Comment by epitsi** [comment]
@TheLastGimbus I've ran into the originally reported problem today myself. I'm guessing that what's happening here is that when you do a takeout of your photos on Google, but instead of just dumping everything you select specific albums, then you get a different folder structure in the takeout .zip file. In particular, all the jpg/json/etc file are stored in a single folder named according to the album's name. Considering the error message by gpth, I am guessing you expect a folder structure with dates.

**Comment by TheLastGimbus** [comment]
@epitsi yeess, but no. gpth works best with year folders, but can work (i think?) with only albums too
