### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by kapitanluffy** [TheLastGimbus/GooglePhotosTakeoutHelper#216]
I have successfully run the app on my Takeout folder but it said it didn't process some files os I ran it again and I got the error.

Here's a screenshot

![gpth-error](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/485799/1aaa7006-632c-41a2-bc06-773bb02ef01b)

**Comment by TheLastGimbus** [comment]
hi!

damn, i really don't know what this is about, i will try to look into it in some free time

**Comment by kapitanluffy** [comment]
No worries. It seems to be about the "fill bar". Take your time :)

**Comment by TheLastGimbus** [comment]
Hi! Sorry this took so long :DDDDDDDDDD

So, I honestly don't have a good idea what's happening, but...

I see that "guessing dates from files" bar didn't even complete... which means there must be a bug with images count?? or somehing?

and then the other bar crashes, saying that it got infinity or nan... the code that would do that:

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/f42822dacd0ff94d7578b711f4aad0bf6822142c/lib/utils.dart#L106-L116

...doesn't seem like it should give a NaN 0_o

could you test your takeout with the newest release? maybe it will magically work??

I would really like to find the issue here :eyes:

**Comment by TheLastGimbus** [comment]
Hi! Sorry this took so long :DDDDDDDDDD

So, I honestly don't have a good idea what's happening, but...

I see that "guessing dates from files" bar didn't even complete... which means there must be a bug with images count?? or somehing?

and then the other bar crashes, saying that it got infinity or nan... the code that would do that:

https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/f42822dacd0ff94d7578b711f4aad0bf6822142c/lib/utils.dart#L106-L116

...doesn't seem like it should give a NaN 0_o

could you test your takeout with the newest release? maybe it will magically work??

I would really like to find the issue here :eyes:

**Comment by kapitanluffy** [comment]
Hey, totally forgot about this issue. I did another takeout today and remembered this tool. It's working great!

Thank you so much for this <3

![image](https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/assets/485799/20f08dc2-88f3-4b3b-88dd-47c9ecfaa89d)

**Comment by TheLastGimbus** [comment]
Happy it works then!!
