### ISSUE TITLE
More tgz issues?

### ISSUE THREAD

**Issue by unintended-consequences** [TheLastGimbus/GooglePhotosTakeoutHelper#222]
Got a fresh 15GB `takeout-2023date.tgz` file, which I manually extracted into a blank directory on Linux.

The folder structure is: `/path/to/Takeout/Google Photos/2023/files`

But running `gpth-linux --input "/path/to/Takeout" --output "/path/to/output"` says `I couldn't find any D:`

Same error for `gpth-linux --input "/path/to/Takeout/Google Photos" --output "/path/to/output"` and `gpth-linux --input "/path/to/Takeout/Google Photos/2023" --output "/path/to/output"`

**Comment by unintended-consequences** [comment]
Does the `--fix` flag do essentially the same thing?

**Comment by TheLastGimbus** [comment]
umm, tgz issues should be completely gone on gpth's side, because it no longer unpacks it itself...

can you show here screenshot of both your folders with your stuff, and terminal saying it didn't find anything?

> --fix flag

ehhh, i should rename that...

> https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/blob/959b78b0a3c2e926c159ba67498a83ffaa6b39f5/bin/gpth.dart#L32-L36

`--fix` is just a handy tool if you have *any* photos laying around and want to set their last modified dates with same heuristics that gpth uses

**Comment by TheLastGimbus** [comment]
Closing for now, hope you resolved - feel free to report any updates
