### ISSUE TITLE
Gets stuck on finding duplicates

### ISSUE THREAD

**Issue by freekeys** [TheLastGimbus/GooglePhotosTakeoutHelper#322]
Thanks so much for this! Amazing tool. I'm trying to use it though on my Mac for a large set of files (1.5TB) hosted on a Synology NAS. It just gets to Findig Duplicates and stays there, presumably still going but then it fails due to losing connection eventually. Any tips on how to do this? I wondered about: 
1) Doing it in batches?
2) I wonder if connecting my Mac by Ethernet vs WiFi would help
3) Buying a 2TB HDD and having the files on there directly plugged into the Mac

Thanks!

**Comment by palijn** [comment]
Same setup as yours : I ran it on the Synology through ssh.
It's actually very fast ! On top of it this allows you to be 100% sure the file timestamps are going to be correct because they're not moved over the network.
Do note that especially if you're using Synology Photos the EXIF dates have to be correct, too.

**Comment by freekeys** [comment]
Thank you so much! This worked perfectly. I can't seem to get the exiftool to work.. when I follow the instructions to just cd into the folder with exiftool and then run "exiftool xxxxxx" I get "exiftool not found". Do you mind sharing what steps you followed please?

**Comment by palijn** [comment]
Well, you need to install exiftool on the NAS because it's not part of DSM.
There are quite a few way to do that. What I did was download the exiftool archive (Image-ExifTool-xx.yy.tar.gz) and extract it on the NAS in /usr/local/bin .
In that place it may not persist after a DSM update but well, it was a one-time shot for me, because I migrated from Google Photos for good.
