### ISSUE TITLE
HEIC Support for EXIF data

### ISSUE THREAD

**Issue by alexhellmann** [TheLastGimbus/GooglePhotosTakeoutHelper#44]
Hello,
is it possible to to add heic support? I used for some years an iPhone and the the photos are in heic format. But the script supports only jpg and tif.

**Comment by TheLastGimbus** [comment]
Huh, this is the thing of `piexif` library that it uses

But reading/writing exif is only one of few ways that this script uses to get correct date - I am planning to improve "finding correct json for photo" soon, so it probably won't need to read exif anymore to set correct "file modified time"

**Comment by tundrablasen** [comment]
HEIC support would really be cool. Currently you script is not helpful for most of the new devices. iPhones use heic since the iPhone 8 (4 years ago) as default. Samsung Galaxy flagships use HEIC since the last 2 years as default.

for me most of my Photo Library is therefore in HEIC.

i saw that some forks already implemented heic support. Maybe you can consider that too

**Comment by TheLastGimbus** [comment]
Oh, can you show me those forks? This is interesting

> not helpful for most of the new devices

But do your exported phots don't have exif? Inserting exif should be only needed when you edited it/it was stripped - do iPhones/Google Photos strip it?

**Comment by tundrablasen** [comment]
> Oh, can you show me those forks? This is interesting
> 
> > not helpful for most of the new devices
> 
> But do your exported phots don't have exif? Inserting exif should be only needed when you edited it/it was stripped - do iPhones/Google Photos strip it?

I clicked through the forks shown on your GitHub. One had heic support via a specific library.

**Comment by TheLastGimbus** [comment]
> One had heic support via a specific library

I want to see this, just which one?

**Comment by TheLastGimbus** [comment]
What I fear of, is that, with current library, I had *so much* weird edge-cases, where dates where formatted in 10 different ways, some even with verbal "friday" wrote in them - and I fear that new exif library would show new, unexpected issues, even tho it promised to be more stable...

I may try out (but don't promise anything) some work in separate branch/beta version, and we will see how well it does...

**Comment by tundrablasen** [comment]
Any chance your script gets HEIC and HEVC support for photo and video? Would be really needed for Apple user. 

Thanks for your feedback. And thanks for the script

**Comment by TheLastGimbus** [comment]
I will take a look at it when I will have some free time laying around...

**Comment by tundrablasen** [comment]
> I will take a look at it when I will have some free time laying around...

I think you created here a 💎 
The need for your script will explode as closer we getting to June 2021 and google photos kills the storage support. Other cloud providers have more appeal (iCloud photos with more privacy focus) and Microsoft OneDrive (cheaper plans).

therefore I would build the script around these two alternatives. What is need for Apple users to switch to iCloud photos and what is needed for Apple and Android users to switch to onedrive 

you already have around 700 stars. This will get huge in the next months

**Comment by TheLastGimbus** [comment]
"a :gem:" and "this will get huge in next months" give me back r/wallstreetbets Game Stop vibes again :laughing: But thank you for kind words :sparkling_heart: 

Altough I personally think that code itself is a big pile of :spaghetti: :hankey:  and not :gem:, at least it works pretty stable and it's ready for another 700 users, and I'm proud of it :+1: 

If you say that new swarm of user will come here in "June 2021", I may give this bigger priority :100:

**Comment by tundrablasen** [comment]
New swarm will definitely come. Many of the non nerds didn’t even Heard- about google change of plans.

So your Script can go 🚀🌓, if you don’t have paper hands

**Comment by TheLastGimbus** [comment]
Damn you were right, it looks like it's getting some more attention nowadays :eyes:

Kinda shame I didn't do this yet...

**Comment by tundrablasen** [comment]
> Damn you were right, it looks like it's getting some more attention nowadays 👀
> 
> Kinda shame I didn't do this yet...

Yeah that’s what I thought would happen. It’s never too late

**Comment by TheLastGimbus** [comment]
Damn it hit **1K** stars :open_mouth: thanks everyone!

I'm writing this to note that I'm not dead and remember about this - tho didn't found it urgent enough :confused: 

If anyone *deperatly* needs it (tho I doubt anyone does after half a year of waiting :laughing: ) - let me know - otherwise, some features of exif like gps (#5) seem really complicated to migrate to other library :confounded:

**Comment by fishwishes** [comment]
@TheLastGimbus I don't know about _desperately_, but I would really love this feature. I have a Google Photos library with over a decade of photos that I'm trying to _correctly_ move to a NAS and it seems like your tool is really the closest option for retaining original quality (processing on a Takeout export rather than API sync). But I also have TONS of HEIC/HEVC content from the last several years with new devices, and I have no idea how to account for those...

**Comment by Petruchio96** [comment]
Was just about to run this on 8 years of iPhone photos... then i saw this issue not supporting HEIC.  I assume that's still the case?

**Comment by TheLastGimbus** [comment]
You should try to run it anyway - it just doesn't support reading/writing their exif values - everything with correct json should work fine :ok_hand: 

// Actually i may change the name since it looks like it's not supported at all :thinking:

**Comment by TheLastGimbus** [comment]
Hi guys!

After 1 year, it is finally done! Exif from HEIC files are officially supported *as a backup from json file not found* - as of `v3.0.0` :tada:

Note that it uses the exif just to set `file last modified` - it does not corret your exifs if you edited the time in the Photos app :disappointed:
