### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by sebastianludwig** [TheLastGimbus/GooglePhotosTakeoutHelper#65]
First of all thank you very much for the great work so far! 🚀

I've got a huge collection of Google Photos which I'd like to pipe through the takeout helper. Initial tests revealed that my takeout contains many edge cases which the helper does not handle correctly yet. I'd be super happy to contribute, but I'd afraid to break existing functionality.

Are there any plans to bring some high level unit test structure into place? Maybe at a full scale integration level first? Something simple like a set of predefined input and reference output folders?

Doesn't even need to be automated in a CI, local execution would already be a win I think.

**Comment by TheLastGimbus** [comment]
Oh, jeez...

Oh, yes yes, you are very welcome here! I just really didn't ever expect this *simple script* to grow to any size like that...

> plans to bring some high level unit test structure into place

I may repeat myself like 3rd time in those comments, but this script is really shitty to be honest. If I would write it righ now, nowing exactly what folder structure/edge cases there are, and *how many people* will use it, I would do this differently:
- for now, it kinda "walks through" the files and does stuff with them
- what I *would do*, is to generate some data strucutres from *all* input files and data, and then play with it

Tests? Yeah, we could write some of those :+1: Righ now, I'm just in the middle of writing a GitHub action that runs the script 30 times on sample folder and measures the time. Perhaps some way to quickly test individual functions, like `find_json_for_file`.

> my takeout contains many edge cases

Could you name some? I already have a routine of "people give me their weird photos, I ~~tell them to send me a donation~~ add it in some PR. Maybe the last time you checked it was some old version - we have a lot of improvments now that protect from edge cases :rocket: 

>  I'd be super happy to contribute

You can wait till I merge those #62 and #63 and maybe I will add some documenation after that

I need to stop lying to myself that this project is done and finished, because it never will be xD - I will add some `contributing.mg` also

**Comment by TheLastGimbus** [comment]
Yes, you can now watch me have fun at #66

**Comment by sebastianludwig** [comment]
> Perhaps some way to quickly test individual functions, like `find_json_for_file`.

Fine grained tests on a function level would "manifest" the current structure and get in the way of refactorings like the data structure one you mentioned.

> I already have a routine of "people give me their weird photos

Correct me if I'm wrong, but we actually only need file _names_, not the actual contents, right? Or do we also sometimes need the JSON file contents? (to be honest I haven't read the code in detail yet)

> I need to stop lying to myself that this project is done and finished, because it never will be xD

I guess that's a given with Google as a moving target on the other side ^^

I'll try to find time this week to open a draft PR to sketch out a first basic test setup proposal.

**Comment by TheLastGimbus** [comment]
> we actually only need file names

Oh no no no, we use *everything* to get right photo data

I will make some general "what this script does" description in `contributing.md` - I can ping you when I'm done, so you won't waste your patiance reverse-engineering code

> first basic test setup proposal

Currently, everything is like:
```python
def main():
  varib = 0
  def other_fun():  # Functions inside main() function
    nonlocal varib  # Ton of global variables <3
```
So I don't know whtether that's really test-able, but I started to think about some general tests that would go like:
 - take folder with pngs (they don't have exifs), but with jsons
 - assert that they have correct dates
 - take folder with photos which' locations were edited in Google Photos editor
 - assert that their output exifs have this location
 - etc

If you want to help:
1. Drop me your edge-case photos - maybe we can do something with them :+1:
2. Also you can give me some exaple photos with stuff to assert - weird formats, stuff where you edited location, duplicates etc

**Comment by sebastianludwig** [comment]
> Oh no no no, we use everything to get right photo data

Everything being EXIF, the file JSON, the folder/album JSON aaand..? (btw, potential last resort fallback: the filename). The point I'm getting at is that we probably don't need the actual image data, like "the pixels". At least I, and I can imagine more people, will be more comfortable sharing their photos which will eventually be hosted in this repo if they don't contain any more potential private information than the filename, EXIF data and the JSON metadata (which could also be cleaned manually if necessary).

> So I don't know whtether that's really test-able, but I started to think about some general tests that would go like:

Yep, that's pretty much what I had in mind. See #68 

> If you want to help:
> 1. Drop me your edge-case photos - maybe we can do something with them 👍
> 2. Also you can give me some exaple photos with stuff to assert - weird formats, stuff where you edited location, duplicates etc

Will do in #68 👍
