### ISSUE TITLE
Smarter json finding

### ISSUE THREAD

**Issue by YounsooChoi** [TheLastGimbus/GooglePhotosTakeoutHelper#92]
```
There was literally no option to set date on test\Photos from 2015\MyPhoto_1116680380_0334.jpeg
There was literally no option to set date on test\Photos from 2015\MyPhoto_1116680380_0335.jpeg
There was literally no option to set date on test\Photos from 2015\MyPhoto_1116680380_0336.jpeg
There was literally no option to set date on test\Photos from 2015\MyPhoto_1116680380_0337.jpeg
There was literally no option to set date on test\Photos from 2015\MyPhoto_1116680380_0338.jpeg
There was literally no option to set date on test\Photos from 2015\MyPhoto_1116680380_0339.jpeg
There was literally no option to set date on test\Photos from 2015\MyPhoto_1116680380_0340.jpeg
There was literally no option to set date on test\Photos from 2015\MyPhoto_1116680380_0341.jpeg
...
!!! There were 53 files where there was absolutely no way to set a correct date! They will probably appear at the top of the others, as their 'last modified' value is set to moment of downloading your takeout :/
 - you have full list in test\unsorted.txt
```

MyPhoto_1116680380_0341.jpeg.json : 
```{
  "title": "MyPhoto_1116680380_0341.jpeg",
  "description": "",
  "imageViews": "7",
  "creationTime": {
    "timestamp": "1516861252",
    "formatted": "2018. 1. 25. 오전 6시 20분 52초 UTC"
  },
  "photoTakenTime": {
    "timestamp": "1432612865",
    "formatted": "2015. 5. 26. 오전 4시 1분 5초 UTC"
  },
```

**Comment by TheLastGimbus** [comment]
Huh, weird. Could you send me an example of those? Preferably in the same "folder structure" way

**Comment by usagicore** [comment]
https://usagicore.org/Takeout.zip

Working as intended with linux, no luck with windows PS/cmd.

```
PS D:\Google Photo\Takeout> google-photos-takeout-helper.exe -i .\test2\ -o .\output\
Heeeere we go!
Counting how many input files we have ahead...
100%|███████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 1277.80formats/s]
Input files: 1
=====================
Fixing files metadata and creation dates...
There was literally no option to set date on test2\Photos from 2015\2015-01-11(1).jpg
100%|████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 166.68files/s]
=====================
=====================
Copying all files to one folder...
(If you want, you can get them organized in folders based on year and month. Run with --divide-to-dates to do this)
100%|████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 200.10files/s]
=====================
=====================
Finding duplicates...
Calculating small hashes...
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?files-by-size/s]
Calculating full hashes...
0files-by-small-hash [00:00, ?files-by-small-hash/s]
Removing duplicates...
0duplicates [00:00, ?duplicates/s]
=====================

DONE! FREEEEEDOOOOM!!!

Final statistics:
Files copied to target folder: 1
Removed duplicates: 0
Files for which we couldn't find json: 0
Files where inserting new exif failed: 0
Files where date was set from name of the folder: 0

!!! There were 1 files where there was absolutely no way to set a correct date! They will probably appear at the top of the others, as their 'last modified' value is set to moment of downloading your takeout :/
 - you have full list in test2\unsorted.txt

Sooo... what now? You can see README.md for what nice G Photos alternatives I found and recommend

If I helped you, you can consider donating me: https://www.paypal.me/TheLastGimbus
Have a nice day!
```

**Comment by TheLastGimbus** [comment]
Oh so it only breaks on Windoza ? Sight, I don't think I can deal with this... this may be some weird character encoding, or god knows what

I can try to add it to tests and see if my GH Actions are passing...

**Comment by 3deo-chris** [comment]
Does it to me too when I ssh into my Synology NAS which is running Linux 4.4.180 (not sure the distro)

**Comment by james2406** [comment]
Seeing the same issue when I ssh into my Synology NAS.

**Comment by mdecourcy** [comment]
Same issue on UnraidOS

**Comment by neostim** [comment]
Also happening in Windows 10 for me, haven't tried linux yet.

**Comment by TheLastGimbus** [comment]
Could you all guys send me an example of photos+jsons which have this issue?

**Comment by james2406** [comment]
I uploaded an example of a file that failed here https://we.tl/t-YRqAOQu29t.

The error I received was:
```
There was literally no option to set date on Takeout/Google Photos/20th Birthday/@eaDir/IMG_4721.JPG/SYNOFILE_THUMB_M.jpg

```

**Comment by james2406** [comment]
After looking at it further, I can see what the issues are in my case:

1. Synology creates thumbnail files (SYNOFILE_THUMB_M.jpg) in the @eaDir folder under indexed folders. It looks like GooglePhotosTakeoutHelper is picking these up, but not able to process them because they don't have a matching .json file.

```
There was literally no option to set date on Takeout/Google Photos/20th Birthday/@eaDir/IMG_4721.JPG/SYNOFILE_THUMB_M.jpg
```

2. When you take a photo with an iPhone, it generates a Live Photo (recording of what happens 1.5 seconds before and 1.5 seconds after you've taken a picture). It looks like Google Photos stores this alongside the image using the same file name, but as an .mp4. Google Takeout doesn't seem to generate a .json file for those .mp4 files, so GooglePhotosTakeoutHelper can't find a match.

```
There was literally no option to set date on Takeout/Google Photos/Trip to Seville/IMG_0503.MP4
```

3. Finally, there are edited photos, which are photos I edited within the Google Photos app. My guess is Google keeps the original photo after you make edits to it, and saves the edit under a different name. These edited photos don't have a matching .json file, so GooglePhotosTakeoutHelper can't find a match.

```
There was literally no option to set date on Takeout/Google Photos/Photos from 2012/IMG_4269-edited.JPG
```

I guess there is nothing that can be done about the way Synology handles thumbnails, and I'm not sure how edited images could be handled, but it would be nice if the Live Photo .mp4 could copy the metadata for the relevant image.

By the way, thanks for creating such an awesome library! This looks like the only solution to get your photos out of Google Photos without days of manual effort.

**Comment by TheLastGimbus** [comment]
Huh... is synology stuff there because you've let synology handle *the takeout folder* **before** running the script? In that case, yeah the script is very sensitive to any edits *before* parsing stuff :confused: 

Otherwise, if the thumbnails ended up there because you were using synology *back when using gphotos*... then huh... this is hard :///

**Comment by james2406** [comment]
Yes, the Synology issue is caused because I added the folder to Synology before I ran the script. I wouldn't expect this library to handle that though.

A potential solution to the Synology thumbnail issue would be to introduce an ignore option that accepts a bit of regex?

It's not an issue for me though anymore as I ram the script on my Mac instead.

**Comment by macintacos** [comment]
I ran this script from my Mac just now, and it missed a few that definitely had a "valid" `photoTakenTime` set in the corresponding json. Here's a dropbox link to one such example: https://www.dropbox.com/t/X4F8AEmWMobAbmHj

The script missed about 80 out of 10k+, so I'll take it on the chin, but I spot-checked a few of them and they all seem to have valid `photoTakenTime` values so I'm not sure what's up.

**Comment by HaZardousss** [comment]
I have more than 50k pictures and almost all of them have this issue. Tried on Windows and mac, no luck :/ how to fix this now?

**Comment by lihuelworks** [comment]
Any updates on this? I have the same issue on Windows 10

**Comment by YounsooChoi** [comment]
Filename length limited to 51 characters including extensions, json "title" has full filename & same issues. 
Same filenames: 62febc99820f9e984d8c3c25988c3c6f160a735c8f2a2a.jpeg & 62febc99820f9e984d8c3c25988c3c6f160a735c8f2a2a.json
Actual filename in json "title": 62febc99820f9e984d8c3c25988c3c6f160a735c8f2a2a0a1db6bfb86ee709a5d06d68cb88c61accaf2445bcd3a5d69dd867e92f9b442e3b0eadad6651f4bb91d57b8bc30b27c0f8ff1d8566cac64b27867e76201078664f40e9d8b1f6b197db.jpeg

Changing json "title" fixes issue. 

example: https://drive.google.com/file/d/1yeHnb6zsrBRTdjnAZUccxtBQ-e5zcZam/view?usp=sharing

**Comment by TheLastGimbus** [comment]
Hi there!

The `v3.0.0` is detecting jsons with "51 characters stripping" very well :+1:

@james2406 thans very much for identifing other cases! Those "`(1)`" and "`-edited`" are in fact 99% cases of json not found

I'll let myself rename this issue and try to work on those two!

**Comment by TheLastGimbus** [comment]
# 🥳🥳🥳

After... **two years** here we have it - `gpth` should now find jsons in 99% of cases - go ahead and test it out!
