### ISSUE TITLE
What to do with unsorted files?

### ISSUE THREAD

**Issue by alehandrof** [TheLastGimbus/GooglePhotosTakeoutHelper#97]
More a question, than an issue:

I really appreciate all the heavy lifting this script does. I'm just puzzled by what to do with the folder of unsorted files. Is there any way to find out what the dates were for them?

**Comment by TheLastGimbus** [comment]
> Is there any way to find out the dates

The answer is: **maybe** 

The script couldn't find the corresponding `.json` file, nor read the exif values correctly - maybe you can! Maybe there is simmilar `.json` file but name is stripped? Maybe there is some exif data but with very weird format (like literally `"Friday at 16 07 2003"`)

Otherwise - it may help to manually search for this photo in Google Photos itself (searching by filename should do)

Otherwise - you may never find it :(

**Comment by alehandrof** [comment]
Thanks for the suggestions! It turned out that most of the unsorted photos are either live photos with both .mov and .jpg files available. Thankfully, there aren't too many of them and I can probably just date them by hand, if need be.

**Comment by TheLastGimbus** [comment]
`v3` is much more reliable in finding the dates, thus this won't be much of a concern, thus i unpin this issue
